practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  
  root "cats#index"
  
  resources :cats, except: [:destroy]
end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    @@CAT_COLORS = ['orange', 'white', 'black', 'gray', 'brown', 'domino']

    validates :birth_date, :name, presence: true
    validates :color, inclusion: {in: @@CAT_COLORS}
    validates :sex, inclusion: {in: ['M', 'F']}
    validate :birth_date_cannot_be_future

    def birth_date_cannot_be_future
        errors.add(:birth_date, "can't be in the future") if birth_date > Date.today
    end

end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render json: @cat
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      render json: @cat
    else 
      @error = @cat.errors.full_messages
      render :new
    end
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :name, :sex, :color, :description)
  end

end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/helpers/cats_helper.rb
module CatsHelper
end

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/cats/edit.html.erb
<form action = "<%= cat_url(@cat) %>" method = "post">
<input type="hidden" name="_method" value="PATCH"/>
    <ul>
        <ul>
            <label for="name">Name: </label><br>
            <input id="name" type = "Update" name = "cat[name]" value = "<%= @cat.name%>"/>
        </ul>
        <ul>
            <label for="<%=@cat.sex%>">Sex: </label><br>
            <input type="radio" id="M" name="cat[sex]" value="<%=@cat.sex%>">
            <label for="<%=@cat.sex%>">Male</label><br>
            <input type="radio" id="F" name="cat[sex]" value="<%=@cat.sex%>">
            <label for="<%=@cat.sex%>">Female</label><br>
        </ul>
        <ul>
            <label for="<%=@cat.birth_date%>">Birthdate:</label><br>
            <input type="date" id="birthday" name="cat[birth_date]" value="<%=@cat.birth_date%>">
        </ul>
        <ul>
            <label for="color">Color:</label><br>
            <select name="cat[color]" id="Colors">
                <option selected="selected"><%=@cat.color%></option>
                <%= ['orange', 'white', 'black', 'gray', 'brown', 'domino'].each do |color|%>
                <option> <%=color%></option>
                <% end %>
            </select>
        </ul>
        <ul>
            <label for="<%=@cat.description%>>">Description:</label><br>
            <input type="text" id="description" name="cat[description]" value="<%=@cat.description%>"><br>
        </ul>
    </ul>
</form>

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/cats/index.html.erb
<h2> Cat Index </h2>
<ul>    
    <% @cats.each do |cat| %>
    <li> <%= cat.name%></li>
    <li> <%= cat.color%></li>
    <li> <%= cat.birth_date%></li>
    <li> <%= cat.description%></li>
    <li><li>
    <% end %>
</ul>

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/cats/new.html.erb
<form action = "<%= cats_url %>" method = "post">
    <ul>
        <ul>
            <label for="name">Name: </label><br>
            <input id="name" type = "Create New" name = "cat[name]" value = "<%= @cat.name%>"/>
        </ul>
        <ul>
            <label for="<%=@cat.sex%>">Sex: </label><br>
            <input type="radio" id="M" name="cat[sex]" value="M">
            <label for="<%=@cat.sex%>">Male</label><br>
            <input type="radio" id="F" name="cat[sex]" value="F">
            <label for="<%=@cat.sex%>">Female</label><br>
        </ul>
        <ul>
            <label for="<%=@cat.sex%>">Birthdate:</label><br>
            <input type="date" id="birthday" name="cat[birth_date]">
        </ul>
        <ul>
            <label for="color">Color:</label><br>
            <select name="cat[color]" id="Colors">
                <option selected="selected"></option>
                <%= ['orange', 'white', 'black', 'gray', 'brown', 'domino'].each do |color|%>
                <option> <%=color%></option>
                <% end %>
            </select>
        </ul>
        <ul>
            <label for="<%=@cat.description%>>">Description:</label><br>
            <input type="textarea" id="description" name="cat[description]"><br>
        </ul>
    </ul>
</form>



<!-- # <h2>New Cat</h2>
# <form action = "<%= cats_url %>" method = "POST">
#     <div>        
#         <label for="name">Name: </label>
#         <input id="name" type = "Create New" name = "cat[name]" value = "<%= @cat.name%>"/>
#     </div>

#     <div>        
#         <label for="color">Color: </label>
#         <input id="color" type = "Create New" name = "cat[color]" value = "<%= @cat.color%>"/>
#     </div>

#     <div>        
#         <label for= "birth_date">Birth_date: </label>
#         <input id="birth_date" type = "Create New" name = "cat[birth_date]" value = "<%= @cat.birth_date%>"/>
#     </div>

#     <div>
#         <label for="sex">Sex: </label>
#         <input id="sex" type = "Create New" name = "cat[sex]" value = "<%= @cat.sex %>"/>
#     </div>

#     <div>        
#         <label for="description">Description: </label>
#         <input id="description" type = "Create New" name = "cat[description]" value = "<%= @cat.description%>"/>
#     </div>
#     <input type="submit" value="<%= 'Create New' %>" />
# </form>

# <%= @error %>
 -->

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2">Cat Show</th>
        <tr/>
    </thead>
    <tbody>
        <tr>
            <td> Name: </td>
            <td><%= @cat.name%></td>
        </tr>
        <tr>
            <td> Birth Date: </td>
            <td> <%= @cat.birth_date%></td>
        </tr>
        <tr>
            <td> Color: </td>
            <td><%= @cat.color%></td>
        </tr>
        <tr>
            <td> Description: </td>
            <td> <%= @cat.description%></td>
        </tr>
    </tbody>
</table>

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>

practice-for-ch-rails-ninety-nine-cats1-long-practice/NinetyNineCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>